name: release
on: push

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-deno@v1
        with:
          deno-version: 1.31.1
      - run: deno task compile
      - run: zip -r linux dist
      - uses: actions/upload-artifact@v3
        with:
          name: uploads
          path: linux.zip
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-deno@v1
        with:
          deno-version: 1.31.1
      - run: deno task compile
      - run: powershell Compress-Archive dist windows.zip
      - uses: actions/upload-artifact@v3
        with:
          name: uploads
          path: windows.zip
  